name: ML Pipeline CI/CD

on: [push, pull_request]

jobs:
  test-and-train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          mkdir -p src/models
          
      - name: Run tests
        run: pytest -v
          
      - name: Train model
        run: |
          cd src
          python train.py
          
      - uses: actions/upload-artifact@v4
        with:
          name: iris-model
          path: src/models/
          retention-days: 5
