name: ML Pipeline CI/CD

on: [push, pull_request]

jobs:
  test-and-train:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify files
        run: |
          ls -la
          ls -la src/

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: ./  # Explicitly set to root
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Create models directory
        run: mkdir -p src/models

      - name: Run tests
        working-directory: ./src
        run: |
          PYTHONPATH=$PYTHONPATH:. pytest tests/ -v

      - name: Train model
        working-directory: ./src
        run: python train.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iris-model
          path: src/models/*
          retention-days: 7
