name: ML Pipeline CI/CD

on: [push, pull_request]

jobs:
  test-and-train:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install correct dependency versions
        run: |
          pip install numpy==1.23.5
          pip install -r requirements.txt
          pip install pytest

      - name: Verify installations
        run: |
          python -c "import numpy; print(f'numpy: {numpy.__version__}')"
          python -c "import sklearn; print(f'sklearn: {sklearn.__version__}')"

      - name: Create models directory
        run: mkdir -p src/models

      - name: Run tests
        working-directory: ./src
        run: |
          PYTHONPATH=$PYTHONPATH:. pytest tests/ -v

      - name: Train model
        working-directory: ./src
        run: python train.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iris-model
          path: src/models/*
          retention-days: 7
